# Generated by Django 5.0 on 2023-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('firstName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=20)),
                ('travelPoints', models.IntegerField()),
            ],
        ),
    ]
